[package]
name = "ada-wbg"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
ada-url = { git = "https://github.com/RReverser/ada-rust-wasm" }
mallocator = "0.1.0"
wasm-bindgen = "0.2.87"
