[package]
name = "ada-wbg"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
ada-url = { path = "../ada-rust", features = ["libcpp"] }
libc_alloc = "1.0.5"
wasm-bindgen = "0.2.87"
